import type { Garment, PrintifyCreateResult } from "./types";

const API = "https://api.printify.com/v1";

interface GarmentConfig {
  blueprintId?: string;
  printProviderId?: string;
  price: number; // cents, charged to the end customer
  label: string;
}

function garmentConfig(garment: Garment): GarmentConfig {
  if (garment === "cap") {
    return {
      blueprintId: process.env.PRINTIFY_CAP_BLUEPRINT_ID,
      printProviderId: process.env.PRINTIFY_CAP_PRINT_PROVIDER_ID,
      price: 2800,
      label: "Snapback Cap",
    };
  }
  return {
    blueprintId: process.env.PRINTIFY_TSHIRT_BLUEPRINT_ID,
    printProviderId: process.env.PRINTIFY_TSHIRT_PRINT_PROVIDER_ID,
    price: 3200,
    label: "Tee",
  };
}

async function printifyFetch(path: string, apiKey: string, init?: RequestInit) {
  const res = await fetch(`${API}${path}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
      ...(init?.headers ?? {}),
    },
  });
  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`Printify ${path} → ${res.status}: ${body.slice(0, 400)}`);
  }
  return res.json();
}

/**
 * Uploads the generated artwork and creates a draft product in the
 * configured Printify shop. See .env.example for the four env vars this
 * needs — any missing one (including the shop-wide API key/shop id) makes
 * this resolve to a stub describing exactly what *would* have been sent,
 * so the "Send to Printify" button in the UI always has something to show.
 *
 * Real-integration notes (printify.com/docs/api):
 *  - POST /v1/uploads/images.json            → upload artwork, get an image id
 *  - GET  /v1/catalog/.../variants.json      → look up sellable variant ids
 *  - POST /v1/shops/{shop_id}/products.json  → create the product
 * This does not publish to a sales channel — Printify still needs a
 * connected storefront (Shopify/Etsy/etc, or its own Pop-Up Store) for
 * customers to actually check out.
 */
export async function createPrintifyProduct(input: {
  garment: Garment;
  title: string;
  imageDataUrl: string;
}): Promise<PrintifyCreateResult> {
  const apiKey = process.env.PRINTIFY_API_KEY;
  const shopId = process.env.PRINTIFY_SHOP_ID;
  const cfg = garmentConfig(input.garment);

  const wouldCreate = {
    title: input.title,
    garment: cfg.label,
    blueprint_id: cfg.blueprintId ?? "(not configured)",
    print_provider_id: cfg.printProviderId ?? "(not configured)",
    price_cents: cfg.price,
  };

  if (!apiKey || !shopId || !cfg.blueprintId || !cfg.printProviderId) {
    return {
      stubbed: true,
      note: "Demo mode — set PRINTIFY_API_KEY, PRINTIFY_SHOP_ID and this garment's blueprint/print-provider IDs in .env to actually create this product in Printify.",
      wouldCreate,
    };
  }

  try {
    const base64 = input.imageDataUrl.split(",")[1] ?? "";
    const upload = (await printifyFetch("/uploads/images.json", apiKey, {
      method: "POST",
      body: JSON.stringify({
        file_name: `${input.title.replace(/\s+/g, "-").toLowerCase()}.png`,
        contents: base64,
      }),
    })) as { id: string };

    const variants = (await printifyFetch(
      `/catalog/blueprints/${cfg.blueprintId}/print_providers/${cfg.printProviderId}/variants.json`,
      apiKey
    )) as { variants: Array<{ id: number }> };

    const variantIds = variants.variants.map((v) => v.id);
    if (variantIds.length === 0) throw new Error("No variants returned for this blueprint/provider");

    const product = (await printifyFetch(`/shops/${shopId}/products.json`, apiKey, {
      method: "POST",
      body: JSON.stringify({
        title: input.title,
        description: `Custom ${cfg.label.toLowerCase()} livery generated by FlameoutRC.`,
        blueprint_id: Number(cfg.blueprintId),
        print_provider_id: Number(cfg.printProviderId),
        variants: variantIds.map((id) => ({ id, price: cfg.price, is_enabled: true })),
        print_areas: [
          {
            variant_ids: variantIds,
            placeholders: [
              {
                position: "front",
                images: [{ id: upload.id, x: 0.5, y: 0.5, scale: 1, angle: 0 }],
              },
            ],
          },
        ],
      }),
    })) as { id: string };

    return {
      stubbed: false,
      productId: product.id,
      note: "Created as a draft product in your Printify shop. Publish it to a connected sales channel (Shopify, Etsy, or a Printify Pop-Up Store) to let customers check out.",
    };
  } catch (err) {
    return {
      stubbed: true,
      note: `Printify request failed, nothing was created: ${
        err instanceof Error ? err.message : String(err)
      }`,
      wouldCreate,
    };
  }
}
